services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0
