# Generated by Django 6.0.3 on 2026-03-17 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroflow_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_water_goal',
            field=models.IntegerField(default=2000, help_text='Daily water goal in ml'),
        ),
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(help_text='Amount in ml')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
