# Generated by Django 6.0.3 on 2026-04-13 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroflow_api', '0004_workoutlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterlog',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='waterlog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='waterlog',
            name='user',
        ),
        migrations.AddField(
            model_name='waterlog',
            name='amount_oz',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 13, 19, 50, 31, 939291, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
