# Generated by Django 6.0.3 on 2026-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroflow_api', '0005_remove_waterlog_amount_remove_waterlog_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_tokens',
            field=models.IntegerField(default=5),
        ),
    ]
