# Generated by Django 6.0.3 on 2026-04-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroflow_api', '0008_remove_user_ai_tokens_fooditem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_calories_goal',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_fat_goal',
            field=models.IntegerField(default=140),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_net_carbs_goal',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_protein_goal',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height_inches',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_lbs',
            field=models.FloatField(default=0.0),
        ),
    ]
