# Generated by Django 6.0.3 on 2026-04-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroflow_api', '0009_userprofile_activity_level_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='burned_calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='duration_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
