# Generated by Django 6.0.3 on 2026-04-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroflow_api', '0011_biometriclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='gif_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
