# Generated by Django 6.0.3 on 2026-05-03 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroflow_api', '0012_exercise_gif_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutsession',
            old_name='date',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='gif_url',
            field=models.URLField(blank=True, help_text='Direct link to a form-guide GIF.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='is_pr',
            field=models.BooleanField(default=False, help_text='True if this set represents a personal record.'),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='weight',
            field=models.FloatField(help_text='Weight in lbs/kg depending on user preference.'),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='ingredients',
            field=models.JSONField(help_text='List of ingredients.'),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='instructions',
            field=models.JSONField(help_text='Ordered list of cooking steps.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ai_tokens',
            field=models.IntegerField(default=5, help_text='Available tokens for AI-powered features like meal recognition.'),
        ),
        migrations.AlterField(
            model_name='waterlog',
            name='amount_oz',
            field=models.IntegerField(help_text='Amount consumed in ounces.'),
        ),
        migrations.CreateModel(
            name='HeartRateDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('bpm', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_data', to='macroflow_api.workoutsession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'timestamp'], name='macroflow_a_session_f8b3c1_idx')],
            },
        ),
    ]
